# Generated by Django 5.2.7 on 2025-10-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receta',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
