# Generated by Django 5.2.7 on 2025-10-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_receta_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('ingredientes', models.TextField()),
                ('pasos', models.TextField()),
                ('tiempo', models.TimeField(blank=True, null=True)),
                ('porcion', models.SmallIntegerField(blank=True, null=True)),
                ('calificacion', models.SmallIntegerField(blank=True, null=True)),
                ('verificacion', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('contraseña', models.CharField(db_column='contrasena', max_length=255)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
