# Generated by Django 5.2.7 on 2025-11-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('receta', models.ForeignKey(db_column='receta_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.receta')),
                ('puntaje', models.SmallIntegerField(db_column='numero')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
    ]
